apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-go
spec:
  template:    
    spec:
      containers:
      - name: hello-go-app
        env:
        - name: ENVIRONMENT
          value: STAGE