apiVersion: v1
kind: Service
metadata:
  name: stage-hello-go
spec:
  ports:
  - name: http
    port: 8888
    protocol: TCP
    targetPort: 8888
  selector:
    app: hello-go
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: hello-go
  name: stage-hello-go
spec:
  selector:
    matchLabels:
      app: hello-go
      tier: web
  template:
    metadata:
      labels:
        app: hello-go
        tier: web
    spec:
      containers:
      - env:
        - name: ENVIRONMENT
          value: STAGE
        image: cruiseh/hello-world-golang-server:v0.3.7
        name: hello-go-app
        ports:
        - containerPort: 8888
