apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-go
  labels:
    app: hello-go
spec:
  selector:
    matchLabels:
      app: hello-go
      tier: web
  template:
    metadata:
      labels:
        app: hello-go
        tier: web
    spec:
      containers:
      - name: hello-go-app
        image: cruiseh/hello-world-golang-server:v0.4.1
        ports:
        - containerPort: 8888
